language: node_js
node_js:
  - 14
os:
  - osx
  - linux
script:
  # install lastest version of npm module
  - npm install --global --verbose npm@7.x.x
  # install modules required for build
  - npm install --verbose
  - if [ "$TRAVIS_OS_NAME" = "macos" ]; then ./node_modules/.bin/electron-builder -m; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./node_modules/.bin/electron-builder -l; fi
deploy:
  provider: releases
  api_key: "76a6d3434e6b0c9efa1a0f2355cde22fb760b75f"
  file_glob: true
  file: dist/HDE*.*
  skip_cleanup: true
  on:
    tags: true