language: node_js
node_js:
  - 14
os:
  - osx
  - linux
script:
  # install lastest version of npm module
  - npm install --global --verbose npm@7.x.x
  # install modules required for build
  - npm install --verbose
  - if [ "$TRAVIS_OS_NAME" = "macos" ]; then ./node_modules/.bin/electron-builder -m; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./node_modules/.bin/electron-builder -l; fi
deploy:
  provider: releases
  api_key: "a1e8f7d49f22c2438eae85f51aa0f6aa8ca87817"
  file_glob: true
  file: dist/HDE*.*
  skip_cleanup: true
  on:
    tags: true
env:
  - GH_TOKEN=a1e8f7d49f22c2438eae85f51aa0f6aa8ca87817